[evpn_vxlan]
dc1-borderleaf1 ansible_host=100.123.24.1 ansible_port=830
dc1-borderleaf2 ansible_host=100.123.24.2 ansible_port=830
dc1-leaf1 ansible_host=100.123.24.5 ansible_port=830
dc1-leaf2 ansible_host=100.123.24.6 ansible_port=830
dc1-leaf3 ansible_host=100.123.24.7 ansible_port=830
dc1-spine1 ansible_host=100.123.24.3 ansible_port=830
dc1-spine2 ansible_host=100.123.24.4 ansible_port=830
dc2-spine1 ansible_host=100.123.24.8 ansible_port=830
dc2-spine2 ansible_host=100.123.24.9 ansible_port=830
